### ISSUE TITLE
Refatoração do código usando 'Clean Code' e arquitetura 'SOLID'

### ISSUE THREAD

**Issue by GustavoLR548** [solid-titans/AEDs3#21]
Nesse exato momento, o código está passando por uma grande refatoração, para deixar ele mais fácil de leitura para todos, e para isso está sendo usando como base as ideias de 'Clean Code' e arquitetura 'SOLID'

A primeira fase da refatoração teve seu término, olhe  para a branch 'refactor' para mais detalhes, mas saiba que por enquanto que essa versão ainda não está funcional, tentar compilar ela apenas resultará em problemas, então tome cuidado a acessar o conteúdo dessa branch.

**Comment by MysteRys337** [comment]
4° processo de refatoração foi concluído, favor olhar para o commit 845820bdeab3482fefa502d56067bcebd55a36e9

**Comment by GustavoLR548** [comment]
4° processo de refatoração foi concluído, favor olhar para o commit 845820b
