### ISSUE TITLE
[BUG] Problema ao inserir a primeira pergunta, quando tem mais de um usuário

### ISSUE THREAD

**Issue by GustavoLR548** [solid-titans/AEDs3#4]
O problema é basicamente este:

**Se você tentar inserir uma pergunta, quando o sistema tem mais de um usuário, essa pergunta será registrada no primeiro usuário, e então será adicionado a todos usuários até chegar no usuário N.**

Possíveis culpados:

Crud.java
PerguntasCRUD.java
ADMPerguntas.java

Para melhor explicar a situação, considere os dois exemplos:

* No primeiro caso eu criei dois usuários: Gustavo e Thiago. e então eu fui em Thiago e tentei inserir uma pergunta. Curiosamente, a pergunta não foi armazenada em Thiago, mas sim em Gustavo. Para ficar ainda mais confuso, se eu adicionar mais uma pergunta, a pergunta agora sim vai para Thiago e esse BUG desaparece e agora as perguntas são adicionadas da maneira como deveria ser.

* No segundo caso eu adicionei três usuários: Gustavo, Thiago e Lucas e então eu fui em Lucas e tentei inserir uma pergunta. No primeiro e segundo caso, não aconteceu nada, nenhuma pergunta foi inserida. Porém no terceiro caso finalmente a pergunta foi adicionada. Quando eu fui olhar as outras contas, eu percebi que a primeira pergunta que eu adicionei em Lucas apareceu em Gustavo, e a segunda apareceu em Thiago. 

Quando todos os usuários possuem perguntas, o BUG não se manifesta, então eu não sei se isso tem haver com a maneira como o Crud funciona,  ou se eu falhei em observar algum erro do "PerguntasCRUD.java".

**Comment by LucasSnatiago** [comment]
Issue consertada junto com o pull request #5!
